const symbolic_constants = {
  ZERO: 0,
  CELCIUS: "c",
  FAHRENHEIT: "f",
  SUBMIT: "submit",
  TODAY: "Today",
  TOMORROW: "Tomorrow",
  DAY_AFTER_TOMORROW: "Day After Tomorrow",
  SUN_IMG_PATH: "summer",
  SUN_IMG_ALT_TEXT: "sun",
  RAIN_IMG_PATH: "torrential-rain",
  RAIN_IMG_ALT_TEXT: "rain",
  SNOW_IMG_PATH: "light-snow",
  SNOW_IMG_ALT_TEXT: "snow",
  CHANCE_OF_SUNSHINE: "chanceofsunshine",
  CHANCE_OF_RAIN: "chanceofrain",
  CHANCE_OF_SNOW: "chanceofsnow",
  CLEAR: "",
  DEGREE_DIFFERENCE: 32,
  FAHRENHEIT_TO_CELCIUS_RATIO: 5 / 9,
  CELCIUS_TO_FAHRENHEIT_RATIO: 9 / 5,
  REMOVE_CLASS_NAME: "remove",
  WEATHER_FORM_ID: "#weather_form",
  WEATHER_CURRENT_ID: "#weather_current",
  WEATHER_UPCOMING_ID: "#weather_upcoming",
  TEMP_CONVERT_FORM_ID: "#temp_form",
  TEMP_TO_CONVERT_ID: "#temp-to-convert",
  MAIN_CONTENT_CONTAINER_ID: "#main_content_container",
  WEATHER_APP_CONTAINER_CLASS: ".weather_app_container",
  WEATHER_APP_CONTAINER_ON_SUBMIT_CLASS_NAME: "weather_app_container_on_submit",
  REGION_STRONG: "Region",
  COUNTRY_STRONG: "Country",
  CURRENTLY_STRONG: "Currently",
  SUNSHINE_STRONG: "Chance of Sunshine",
  RAIN_STRONG: "Chance of Rain",
  SNOW_STRONG: "Chance of Snow",
  AVG_STRONG: "Average Temperature",
  MAX_STRONG: "Max Temperature",
  MIN_STRONG: "Minimum Temperature",
  NEAREST_AREA_STRONG: "Nearest Area",
  AREA_STRONG: "Area",
  WEATHER_ARTICLE_CLASS_NAME: "weather-article",
  UPCOMING_WEATHER_ARTICLE_CLASS_NAME: "upcoming_weather_article",
  TEMP_WIDGET_ON_CLASS_NAME: "temp_widget_on",
  TEMP_WIDGET_OFF_CLASS_NAME: "temp_widget_off",
  HIDDEN_CLASS_NAME: "hidden",
  HIDDEN_CLASS: ".hidden",
  CHANCE_OF_SUNSHINE_INDEX: 0,
  CHANCE_OF_RAIN_INDEX: 1,
  CHANCE_OF_SNOW_INDEX: 2,
  _SPACE_: " ",
  _ENCODED_SPACE_: "%20",
  _DASH_: "-",
  _DASH_SPACE_: " - ",
  NONE: "none",
  SRC_ATTRIBUTE: "src",
  ALT_ATTRIBUTE: "alt",
  USER_INPUT_INDEX_INSIDE_URL: 3,
  ERROR_MSG_USER_INPUT_EMPTY: "Please provide a valid input",
};

export default symbolic_constants;
